config/routes.rb
Rails.application.routes.draw do
  root 'liqpay_requests#index'

  resources :liqpay_requests, only: [:index, :new, :create, :show]
  post '/liqpay_payment', to: 'liqpay_requests#liqpay_payment'
end

app/models/liqpay_request.rb
class LiqpayRequest < ActiveRecord::Base
  attr_accessible :amount, :description, :status

  validates_presence_of :amount, :description

  enum status: { start: 0, success: 1, failed: 2 }

  after_create :set_status

  private

  def set_status
    update_attribute(:status, 0)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/liqpay_requests_controller.rb
class LiqpayRequestsController < ApplicationController
  protect_from_forgery except: :liqpay_payment

  def index
    @liqpay_requests = LiqpayRequest.all
  end

  def new
    @liqpay_request = LiqpayRequest.new(
      amount: '1',
      description: 'Technic'
    )
  end

  def create
    @liqpay_request = LiqpayRequest.create(params[:liqpay_request])

    liqpay = Liqpay.new
    request = liqpay.api('invoice/send', {
                                         sandbox: 1,
                                         email: 'test@example.com',
                                         currency: 'UAH',
                                         amount: @liqpay_request.amount.to_i,
                                         order_id: [*0..9].sample(200).join.to_i,
                                         server_url: liqpay_payment_url,
                                         result_url: liqpay_request_url(@liqpay_request),
                                         goods: [{
                                                   amount: 1,
                                                   count: 1,
                                                   unit: 'pcs',
                                                   name: 'Order'
                                                 }]
                                       })

    redirect_to request['href']
  end

  def show
    @liqpay_request = LiqpayRequest.find(params[:id])
  end

  def liqpay_payment
    puts

    # data[:status] -> success
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/liqpay_requests_helper.rb
module LiqpayRequestsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Liqpayment
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %div(id = "#{controller_name}")
      = yield

app/views/liqpay_requests/index.html.haml
%p
  Liqpay Requests

%table
  %th
    %td
      Description
    %td
      Amount

- @liqpay_requests.each do |lr|
  %tr
    %td
      = link_to lr.description, liqpay_request_path(lr)
    %td
      = lr.amount

%p
  = link_to 'Create New Liqpay Request', new_liqpay_request_path

app/views/liqpay_requests/new.html.haml
%h1
  New Liqpay Request

%p
  = form_for @liqpay_request do |f|
    %p
      = f.label :amount
      = f.text_field :amount

    %p
      = f.label :description
      = f.text_field :description

    %p
      = f.submit

app/views/liqpay_requests/show.html.haml
%p
  = @liqpay_request.description

%p
  = @liqpay_request.amount

%p
  = link_to 'Back', liqpay_requests_path